[package]
name = "bux"
version = "0.1.0"
authors = ["Alex <236286348+alex-dozer@users.noreply.github.com>"]
edition = "2021"


[dependencies]
dioxus = { version = "0.7.1", features = [] }

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
