[package]
name = "ben_wire"
version = "0.1.0"
edition.workspace = true
license.workspace = true


[dependencies]
serde = { version = "1.0.228", features = ["derive"], optional = true }
thiserror = "2.0.17"
anyhow = "1.0.100"

[features]
default = ["serde"]
serde = ["dep:serde"]
json = ["serde"]
