[package]
name = "ben_contracts"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false
bench = false

[dependencies]
linkme = "0.3.35"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1"
