[package]
name = "lucius-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"
doctest = false
bench = false

[[bin]]
name = "lucius-core"
path = "src/main.rs"

[dependencies]
