[package]
name = "bitspec_engine"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
name = "bitspec_engine"
path = "src/lib.rs"
doctest = false
bench = false

[dependencies]
ben_wire = { "path" = "../ben_wire" }
smallvec = "1.15.1"
